### ISSUE TITLE
ValueError: too many values to unpack (expected 2) on Auto-Calibration

### ISSUE THREAD

**Issue by eyildiz-ugoe** [UcefMountacer/Roots_Point_Cloud#1]
The following command is supposed to initiate the auto-calibration process. I've activated my environment already and executed the command as follows:

`(3d_reconst): ~/Desktop/3d_reconst$ python main.py --op C --v1 /home/eyildiz/Desktop/3d_reconst/data/2018/02/22/11/MVI_0252.MOV --v2 /home/eyildiz/Desktop/3d_reconst/data/2018/02/22/11/MVI_0590.MOV --filter_th 0.9 --rms_th 10.0`

Here is the output:

```
running auto-calibration
running auto-calibration using 145 images
step : 0
Traceback (most recent call last):
  File "main.py", line 138, in <module>
    K, err = calibrate_intrinsic(obj_pts, image_pts, img_size)
ValueError: too many values to unpack (expected 2)
```

I am using OpenCV 4.5.3 and Python 3.8.

**Comment by UcefMountacer** [comment]
Its fixed, the issue was related to calibrate_intrinsic function

**Comment by eyildiz-ugoe** [comment]
WIth the latest commit 16eca240e65d51c3f9e638dbbc576c62a37c557a , it worked, thanks.
